### ISSUE TITLE
Enabling Tailwind JIT?

### ISSUE THREAD

**Issue by mwoodpatrick** [juristr/blog-series-nextjs-nx#1]
I'm not seeing 

> // apps/site/tailwind.config.js
> 
> module.exports = {
>   mode: 'jit',
>   ...
> };

in

apps/site/tailwind.config.js

what am I missing?

**Comment by juristr** [comment]
You're right. I forgot to enable it there, as at the time of writing the article, JIT mode was in early testing from the Tailwind team.

I'll update the config to include it. Also for your question related to having JIT mode watching enabled, feel free to subscribe here: https://github.com/nrwl/nx/issues/6332#issuecomment-878509542.

I'm tracking progress on that issue

**Comment by juristr** [comment]
Closing as the Tailwind tracking happens in the linked issue. There are some improvements on the way overall.
