### ISSUE TITLE
video versus Youtube

### ISSUE THREAD

**Issue by mwoodpatrick** [juristr/blog-series-nextjs-nx#2]
The article:

https://blog.nrwl.io/component-hydration-with-mdx-in-next-js-and-nx-90f46ea0431c

shows:

export const mdxElements = {
	video: Youtube
}

but the github repo has:

export const mdxElements = {
  Youtube,
  a: CustomLink,
};

**Comment by juristr** [comment]
In the article I mention that you can re-map the Youtube component to "video" as a potential option, but I'm not pursuing that further in the code example.

Also the "a" tag mapping is just to have another example of mapping all hyperlinks to a React "Link" component :)
