### ISSUE TITLE
localhost in yarn.lock

### ISSUE THREAD

**Issue by mwoodpatrick** [juristr/blog-series-nextjs-nx#5]
Is there a reason why some of the dependencies in yarn.lock reference localhost?

For example:

glob-base@^0.3.0:
  version "0.3.0"
  resolved "http://localhost:4873/glob-base/-/glob-base-0.3.0.tgz#dbb164f6221b1c0b1ccf82aea328b497df0ea3c4"
  integrity sha1-27Fk9iIbHAscz4Kuoyi0l98Oo

**Comment by juristr** [comment]
@mwoodpatrick yeah sorry for that, slipped in when doing some local testing :). I think I've fixed it, otherwise I'll push it up with the next changes
